### ISSUE TITLE
g and G should change Gain setting but do change the frequency

### ISSUE THREAD

**Issue by zanco** [r4d10n/waterfall#1]
Line 341

Spectrum.prototype.incrementGain = function() { 
    var freq = { freq : this.centerHz + this.tuningStep };
    this.ws.send(JSON.stringify(freq));               
}

So pressing g or G decreases and increases the frequency instead of the gain.

**Comment by r4d10n** [comment]
Gain and FPS support has been implemented in the latest commit c000506.
